version: '3'
services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
  database:
    container_name: hyperf-skeleton-pgsql
    image: postgres:10
    environment:
      POSTGRES_USER: hyperf
      POSTGRES_PASSWORD: hyperf
      POSTGRES_DB: hyperf
    ports:
        - 5432:5432
    volumes:
        - ./docker/data:/var/lib/postgresql/data
